name: MLflow CI Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install conda and MLflow dependencies
        run: |
          pip install mlflow==2.17.0

      - name: Configure MLflow Tracking
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/liqolina/Workflow-CI.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=liqolina" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.TOKEN_DAGSHUB }}" >> $GITHUB_ENV

      - name: Run MLflow Project
        env:
          DAGSHUB_TOKEN: ${{ secrets.TOKEN_DAGSHUB }}
        run: |
          mlflow run . --env-manager=local -P data_path=student_depression_preprocessing.csv | tee mlflow_output.log
          grep "MLFLOW_RUN_ID=" mlflow_output.log | cut -d'=' -f2 > run_id.txt

      - name: Install Git LFS
        run: |
          sudo apt-get update && sudo apt-get install git-lfs -y
          git lfs install

      - name: Track MLflow model artifacts
        run: |
          RUN_ID=$(cat run_id.txt)
          git lfs track "mlruns/0/$RUN_ID/artifacts/model/**"
          git add .gitattributes

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit MLflow artifacts
        run: |
          RUN_ID=$(cat run_id.txt)
          git add mlruns/0/$RUN_ID/artifacts/model/
          git diff --quiet && echo "No new artifacts to commit" || git commit -m "chore: add MLflow model artifacts for run $RUN_ID [skip ci]"

      - name: Push artifacts to GitHub
        run: git push origin main

      - name: Build MLflow serving Docker image
        run: |
          RUN_ID=$(cat run_id.txt)
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "mh-model"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag mh-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mh-model:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mh-model:latest
