name: Student Depression Model CI Workflow

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Setup Python
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow pandas numpy scikit-learn matplotlib xgboost

      # 4. Run MLflow project
      - name: Run MLflow Project
        run: |
          mlflow run MLProject  --env-manager=local \
            -P n_estimators=150 \
            -P max_depth=42

      # 5. Get latest run_id
      - name: Get latest MLflow run_id
        run: |
          echo "RUN_ID=$(ls -td mlruns/0/*/ | head -n1 | xargs basename)" >> $GITHUB_ENV

      # 6. Setup Git LFS & track model artifacts
      - name: Install Git LFS
        run: |
          sudo apt-get update && sudo apt-get install git-lfs -y
          git lfs install

      - name: Track and Add Model Artifacts
        run: |
          for MODEL_DIR in mlruns/0/$RUN_ID/artifacts/*_model; do
            if [ -d "$MODEL_DIR" ]; then
              echo "Tracking $MODEL_DIR/**"
              git lfs track "$MODEL_DIR/**"
              git add "$MODEL_DIR"
            else
              echo "No model directory found at $MODEL_DIR"
            fi
          done
          
          if [ -f ".gitattributes" ]; then
            git add .gitattributes
          else
            echo "No .gitattributes file to add"
          fi

      # 7. Commit & push model artifacts
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit MLflow artifacts
        run: |
          git add mlruns/0/$RUN_ID/artifacts/model/
          git diff --quiet && echo "No new artifacts to commit" || git commit -m "chore: add MLflow model artifacts for run $RUN_ID [skip ci]"

      - name: Push to GitHub
        run: git push origin main

      # 8. Build Docker image from MLflow model
      - name: Build Docker image for MLflow model
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "ml-model"

      # 9. Docker login and push to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag ml-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ml-model:latest
