name: CI/CD MLflow

permissions:
  contents: write

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Set up Python
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Run MLflow Project
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          pip install mlflow
          mlflow run . --env-manager=local
        
      # 5. Get latest MLflow run_id
      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n1 | xargs basename)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

      # 6. Install Git LFS and track model artifacts
      - name: Install Git LFS
        run: |
          sudo apt-get update && sudo apt-get install git-lfs -y
          git lfs install

      - name: Track MLflow model artifacts
        run: |
          git lfs track "mlruns/0/$RUN_ID/artifacts/model/**"
          git add .gitattributes

      # 7. Commit and push artifacts
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit model artifacts
        run: |
          git add mlruns/0/$RUN_ID/artifacts/model/
          git diff --quiet && echo "No new artifacts to commit" || git commit -m "chore: add MLflow model artifacts for run $RUN_ID [skip ci]"

      - name: Push artifacts to GitHub
        run: git push origin master

      # 8. Build MLflow model Docker image
      - name: Build MLflow Docker image
        run: |
          mlflow models build-docker \
            --model-uri "runs:/$RUN_ID/model" \
            --name "mh-model"

      # 9. Docker Hub login and push
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag mh-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mh-model:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mh-model:latest
