name: Student Depression Dataset 

permissions:
  contents: write

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      # 1) 
      - name: Checkout_repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2) 
      - name: Setup_Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      # 3) 
      - name: Install_deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pandas scikit-learn numpy

      # 4) 
      - name: Run_preprocessing
        run: |
          python preprocessing/automate_LutfiAundrieHermawan.py \
            --input student_depression_dataset.csv \
            --output preprocessing/student_depression_dataset_preprocessing

      # 5) 
      - name: Debug_contents
        run: |
          echo "Contents of preprocessing folder:"
          ls -R preprocessing/student_depression_dataset_preprocessing/

      # 6) 
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit preprocessed data
        run: |
          git add preprocessing/student_depression_dataset_preprocessing/
          git diff --quiet && echo "No changes to commit" || git commit -m "chore: update preprocessed dataset [skip ci]"

      - name: Push changes
        run: git push origin master

      # 7)
      - name: Upload preprocessed dataset artifact
        uses: actions/upload-artifact@v4
        with:
          name: student-depression-preprocessed
          path: preprocessing/student_depression_dataset_preprocessing/
